language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_e7c75155e25f_key -iv $encrypted_e7c75155e25f_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
